title: Jinge Liu
position: Assistant Professor in Finance
affiliation: City University of Hong Kong
email: jingeliu (at) cityu.edu.hk
logo: /assets/img/Tom_Tom_and_Jerry.png
description: Assistant Professor in Finance, City University of Hong Kong
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
github.is_project_page: false
github.is_user_page: false
